// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasketComponent: typeof import('./src/components/BasketComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElRate: typeof import('element-plus/es')['ElRate']
    GameCard: typeof import('./src/components/GameCard.vue')['default']
    GameCardDetails: typeof import('./src/components/GameCardDetails.vue')['default']
    HeaderMenuComponent: typeof import('./src/components/HeaderMenuComponent.vue')['default']
    HeaderMenuDropdown: typeof import('./src/components/HeaderMenuDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheSubHeader: typeof import('./src/components/TheSubHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
